rails/config/routes.rb
Rails.application.routes.draw do
    resources :products
    resources :categories
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "products#index"
    get '/products_by_category', to: 'products#products_by_category'

end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

rails/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, counter_cache: true
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories[.json][.xml]
  def index
    @categories = Category.order("name")
    respond_to do |format|
      format.html
      format.json { render json: @categories }
      format.xml  { render xml: @categories.as_json(
          except: [:id, :created_at],
          root: true,
          include: { products: {only: [:name, :quantity]} },
          ) }
    end
  end

  # GET /categories/1[.json][.xml]
  def show
    respond_to do |format|
      format.html
      format.json { render json: @category }
      format.xml  { render xml: @category.as_json }
    end
  end


  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

rails/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

    # GET /products_by_category.xml
    def products_by_category
        @categories = Category.all
    end

    # GET /products[.json][.xml]
    def index
        @products = Product.order("name")
    end

    # GET /products/1[.json][.xml]
    def show
    end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :quantity, :category_id)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/categories_helper.rb
module CategoriesHelper
end

rails/app/helpers/products_helper.rb
module ProductsHelper
end

rails/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

<% if category.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<div class="row">
    <div class="col-12 mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
        <div id="nameHelp" class="form-text">Unique name.</div>
    </div>
</div>

<div class="row border-top">
    <div class="col-12 mt-3 mb-3">
        <%= form.submit class: 'btn btn-primary' %>
    </div>
</div>

<% end %>

rails/app/views/categories/edit.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">Editing Category '<%= @category.id %>'</h3>
    </div>
</div>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<%= render 'form', category: @category %>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

rails/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <% @categories.each do |category| %>
      <tr>
        <td onclick="window.location='<%= category_path(category) %>';">
            <%= category.name %></td>
        <td onclick="window.location='<%= category_path(category) %>';">
            <%= category.products_count %></td>
        <td class="text-end">
<%= link_to category do %>
  <i class="bi bi-eye"></i> Show
<% end %>
            &nbsp;|&nbsp;
<%= link_to edit_category_path(category) do %>
  <i class="bi bi-pencil"></i> Edit
<% end %>
            &nbsp;|&nbsp;
<%= link_to category, method: :delete, data: { confirm: 'Permanantly delete this Category?' } do %>
  <i class="bi bi-trash"></i> Destroy
<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

rails/app/views/categories/new.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">New Category</h3>
    </div>
</div>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<%= render 'form', category: @category %>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Back', categories_path %>

rails/app/views/categories/show.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">Category '<%= @category.id %>'</h3>
    </div>
</div>

<% if notice %><p id="notice"><%= notice %></p><% end %>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">ID</span><br/>
        <span class="fs-5"><%= @category.id %></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">Name</span><br/>
        <span class="fs-5"><%= @category.name %></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">Products (<%= @category.products.count %>)</span><br/>
        <span class="fs-5"><ul>
            <% @category.products.each do |product| %>
                <li><%= link_to product.name, product %></li>
            <% end %>

        </ul></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">products_count</span><br/>
        <span class="fs-5"><%= @category.products_count %></span>
    </div>
</div>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

rails/app/views/layouts/_footer.html.erb
<hr/>
<div class="row container-fluid">
    <div class="col">
        LFT
    </div>
    <div class="col text-center">
        <%= request.original_url %>
    </div>
    <div class="col text-end">
        RGT
    </div>
</div>

rails/app/views/layouts/_header.html.erb
<div class="row container-fluid">
    <div class="col-1">
        <%= link_to 'Products', products_path %>
    </div>
    <div class="col-1">
        <%= link_to 'Categories', categories_path %>
    </div>
    <div class="col text-end">
        RGT
    </div>
</div>
<hr/>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
<%= render "layouts/header" %>

<div class="container-fluid">
<%= yield %>
</div>

<%= render "layouts/footer" %>
</body>
</html>

rails/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>

<% if product.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<div class="row">
    <div class="col-12 mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
        <div id="nameHelp" class="form-text">Give me names.</div>
    </div>
    <div class="col-12 mb-3">
        <%= form.label :quantity, class: 'form-label' %>
        <%= form.number_field :quantity, class: 'form-control' %>
    </div>
    <div class="col-12 mb-3">
        <%= form.label :category_id, class: 'form-label' %>
        <%= form.collection_select :category_id, Category.order(:name), :id, :name, {}, {class: 'form-select'}  %>
    </div>
</div>

<div class="row border-top">
    <div class="col-12 mt-3 mb-3">
        <%= form.submit class: 'btn btn-primary' %>
    </div>
</div>

<% end %>

rails/app/views/products/edit.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">Editing Product '<%= @product.id %>'</h3>
    </div>
</div>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<%= render 'form', product: @product %>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

rails/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-hover">
<thead>
    <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Category</th>
        <th colspan="3"></th>
    </tr>
</thead>
<tbody class="table-group-divider">
    <% @products.each do |product| %>
    <tr>
        <td onclick="window.location='<%= product_path(product) %>';">
            <%= product.name %></td>
        <td onclick="window.location='<%= product_path(product) %>';">
            <%= product.quantity %></td>
        <td onclick="window.location='<%= product_path(product) %>';">
            <%= link_to product.category.name, product.category %></td>
        <td class="text-end">
<%= link_to product do %>
  <i class="bi bi-eye"></i> Show
<% end %>
            &nbsp;|&nbsp;
<%= link_to edit_product_path(product) do %>
  <i class="bi bi-pencil"></i> Edit
<% end %>
            &nbsp;|&nbsp;
<%= link_to product_path(product), method: :delete, data: { confirm: 'Permanantly delete this Product?' } do %>
  <i class="bi bi-trash"></i> Destroy
<% end %>
        </td>
    </tr>
    <% end %>
</tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

rails/app/views/products/new.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">New Product</h3>
    </div>
</div>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<%= render 'form', product: @product %>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Back', products_path %>

rails/app/views/products/show.html.erb
<div id="item_edit_panel" class="card">
    <div class="card-header">

<div class="row">
    <div class="col">
<h3 class="card-title text-nowrap">Product '<%= @product.id %>'</h3>
    </div>
</div>

<% if notice %><p id="notice"><%= notice %></p><% end %>

    </div> <!-- end class="card-header" -->
    <div class="card-body">

<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">ID</span><br/>
        <span class="fs-5"><%= @product.id %></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">Name</span><br/>
        <span class="fs-5"><%= @product.name %></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">Quantity</span><br/>
        <span class="fs-5"><%= @product.quantity %></span>
    </div>
</div>
<div class="row">
    <div class="col-12 col-sm-6 mb-2">
        <span class="fs-6 fw-light mb-0">Category</span><br/>
        <span class="fs-5"><%= link_to @product.category.name, @product.category %></span>
    </div>
</div>

    </div> <!-- end class="card-body" -->
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>